#!/bin/bash

DOCKERFILE_PATH="."
DOCKER_HUB_USERNAME="karthidevops1"
DOCKER_IMAGE_NAME="newimage"
DOCKER_IMAGE_TAG="latest"
DOCKER_REPOSITORY="prod"
docker build -t "$DOCKER_IMAGE_NAME" "$DOCKERFILE_PATH"
docker login -u "$DOCKER_HUB_USERNAME" -p Kandasamy@123
#docker push "$DOCKER_HUB_USERNAME/$DOCKER_REPO_NAME:$DOCKER_IMAGE_TAG"
docker tag "$DOCKER_IMAGE_NAME:$DOCKER_IMAGE_TAG" "$DOCKER_HUB_USERNAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG"
docker push "$DOCKER_HUB_USERNAME/$DOCKER_REPOSITORY:$DOCKER_IMAGE_TAG"

